---
title: "data"
author: "Sahir"
date: "January 22, 2017"
output:
  md_document:
    variant: markdown_github
---

# References


<ol>
<li>
<p>Efron, Bradley. 1977. "The Efficiency of Cox's Likelihood Function for Censored Data." <em>Journal of the American Statistical Association</em> 72 (359). Taylor &amp; Francis Group: 557–65.</p>
</li>
<li>
<p>Hanley, James A, and Olli S Miettinen. 2009. "Fitting Smooth-in-Time Prognostic Risk Functions via Logistic Regression." <em>The International Journal of Biostatistics</em> 5 (1).</p>
</li>
<li>
<p>Mantel, Nathan. 1973. "Synthetic Retrospective Studies and Related Topics." <em>Biometrics</em>. JSTOR, 479–86.</p>
</li>
<li>
<p>Saarela, Olli. 2015. "A Case-Base Sampling Method for Estimating Recurrent Event Intensities." <em>Lifetime Data Analysis</em>. Springer, 1–17.</p>
</li>
<li>
<p>Saarela, Olli, and Elja Arjas. 2015. "Non-Parametric Bayesian Hazard Regression for Chronic Disease Risk Assessment." <em>Scandinavian Journal of Statistics</em> 42 (2). Wiley Online Library: 609–26.</p>
</li>
<li>
<p>Scrucca, L, A Santucci, and F Aversa. 2010. "Regression Modeling of Competing Risk Using R: An in Depth Guide for Clinicians." <em>Bone Marrow Transplantation</em> 45 (9). Nature Publishing Group: 1388–95.</p>
</li>
</ol>
